import React, { useEffect, useState } from "react"
import { useUnit } from "../context/UnitContext"
import { api } from "../api/client"
import SimpleLoader from "../components/SimpleLoader"
import TemplateHeader from "../components/TemplateHeader"
import QuestionCard from "../components/QuestionCard"
import FeedbackCard from "../components/FeedbackCard"

/**
 * 4 rounds map to the first 4 subtopics generated by /generate/mastery-all.
 * Subtopic names must match the backend's subtopic list exactly so the
 * pickQuestion helper can look them up in preGeneratedQuestions.
 */
const MASTERY_ROUNDS = [
  { subtopic: "natural and whole numbers", dimension: "knowledge", level: "easy" },
  { subtopic: "integers",                  dimension: "knowledge", level: "medium" },
  { subtopic: "comparison and ordering",   dimension: "skills",    level: "medium" },
  { subtopic: "arithmetic operations",     dimension: "skills",    level: "hard" },
]

// Progress pill labels shown above each question
const SUBTOPICS = [
  { key: "natural",    label: "Natural Numbers" },
  { key: "integers",   label: "Integers" },
  { key: "comparison", label: "Comparison" },
  { key: "arithmetic", label: "Operations" },
  { key: "properties", label: "Properties" },
  { key: "lcm",        label: "LCM and HCF" }
]

const PILL_STYLE = {
  padding: "4px 10px",
  borderRadius: "16px",
  fontSize: "11px",
  fontWeight: "bold",
  fontFamily: "Arial"
}

function pillColors(status) {
  if (status === "passed")  return { background: "#D5F5E3", color: "#1E8449" }
  if (status === "failed")  return { background: "#FADBD8", color: "#C0392B" }
  if (status === "current") return { background: "#FEF9E7", color: "#E87722" }
  return { background: "#F2F3F4", color: "#BDC3C7" }
}

/**
 * Extract one question from the pre-generated pool.
 * Backend stores: knowledge[0]=easy, knowledge[1]=medium;
 *                 skills[0]=medium,   skills[1]=hard
 */
function pickQuestion(pregen, subtopic, dimension, level) {
  const key = subtopic.replace(/ /g, "_")
  const qs = pregen?.[key]?.[dimension] || []
  // knowledge: easy→0, medium→1 | skills: medium→0, hard→1
  const idx = (level === "easy" || (dimension === "skills" && level === "medium")) ? 0 : 1
  return qs[idx] || qs[0] || null
}

export default function MasteryGate({ onNavigate }) {
  const { sessionId, addCompletedTemplate, updatePerformance } = useUnit()

  // Fix 2 — pre-generation state
  const [masteryReady, setMasteryReady]             = useState(false)
  const [preGeneratedQuestions, setPreGeneratedQuestions] = useState(null)

  // Per-round state
  const [question,  setQuestion]  = useState(null)
  const [loading,   setLoading]   = useState(false)
  const [feedback,  setFeedback]  = useState(null)
  const [checking,  setChecking]  = useState(false)
  const [round,     setRound]     = useState(0)
  const [score,     setScore]     = useState(0)
  const [done,      setDone]      = useState(false)

  // Pill status per subtopic
  const [subtopicStatus, setSubtopicStatus] = useState({
    natural: "current",
    integers: "pending",
    comparison: "pending",
    arithmetic: "pending",
    properties: "pending",
    lcm: "pending"
  })

  // On mount: pre-generate ALL questions, then load round 0 instantly
  useEffect(() => {
    if (!sessionId) { onNavigate("teacherInput"); return }
    initMastery()
  }, [sessionId]) // eslint-disable-line

  const initMastery = async () => {
    let pregen = null
    try {
      const result = await api.generateMasteryAll(sessionId)
      if (result.questions) {
        pregen = result.questions
        setPreGeneratedQuestions(pregen)
      }
    } catch (e) {
      // Silently fall through — loadQuestion will use the per-question API
    }
    setMasteryReady(true)
    // Pass pregen directly so we don't depend on state being flushed yet
    loadQuestion(0, pregen)
  }

  /**
   * Load the question for round r.
   * Uses pregen argument (at init time) or preGeneratedQuestions state (for later rounds).
   */
  const loadQuestion = (r, pregen = null) => {
    const pool = pregen ?? preGeneratedQuestions
    const { subtopic, dimension, level } = MASTERY_ROUNDS[r]
    setFeedback(null)

    if (pool) {
      const q = pickQuestion(pool, subtopic, dimension, level)
      if (q) {
        setQuestion({ ...q })
        setLoading(false)
        return
      }
    }

    // Fallback: individual API call
    setLoading(true)
    api.generateMasteryQuestion(sessionId, subtopic, dimension, level)
      .then(res => { setQuestion({ ...res }); setLoading(false) })
      .catch(() => setLoading(false))
  }

  const handleAnswer = async (option) => {
    if (!question) return
    setChecking(true)
    const { subtopic, dimension, level } = MASTERY_ROUNDS[round]
    const result = await api.checkAnswer(
      sessionId, question.text, question.correct_answer,
      option, subtopic, dimension, level
    )
    // Fix 1 (carry-over) — compute newScore once, no double-counting
    const newScore = result.is_correct ? score + 1 : score
    setScore(newScore)
    setFeedback(result)
    setChecking(false)
  }

  const handleNext = () => {
    const nextRound = round + 1

    // Advance pill status
    const currentKey = SUBTOPICS[round]?.key
    const nextKey    = SUBTOPICS[nextRound]?.key
    setSubtopicStatus(prev => ({
      ...prev,
      ...(currentKey ? { [currentKey]: feedback?.is_correct ? "passed" : "failed" } : {}),
      ...(nextKey && nextRound < MASTERY_ROUNDS.length ? { [nextKey]: "current" } : {})
    }))

    if (nextRound >= MASTERY_ROUNDS.length) {
      const result = `${score} / ${MASTERY_ROUNDS.length}`
      updatePerformance("masteryGateResult", result)
      setDone(true)
    } else {
      setRound(nextRound)
      loadQuestion(nextRound)
    }
  }

  const handleContinue = () => {
    addCompletedTemplate("masteryGate")
    onNavigate("projectPlanning")
  }

  // Fix 2 — show spinner while all questions are being pre-generated
  if (!masteryReady) {
    return (
      <div style={{
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        minHeight: "60vh",
        gap: "24px"
      }}>
        <div style={{
          width: "56px",
          height: "56px",
          border: "4px solid #F2F3F4",
          borderTop: "4px solid #E87722",
          borderRadius: "50%",
          animation: "spin 1s linear infinite"
        }} />
        <p style={{ fontSize: "16px", color: "#5D6D7E", fontFamily: "Arial" }}>
          We are almost there...
        </p>
        <style>{`
          @keyframes spin {
            0%   { transform: rotate(0deg); }
            100% { transform: rotate(360deg); }
          }
        `}</style>
      </div>
    )
  }

  // Fix 3 — SimpleLoader for the rare fallback per-question load
  if (loading) return <SimpleLoader />

  if (done) {
    const total  = MASTERY_ROUNDS.length
    const passed = score >= Math.ceil(total * 0.75)
    return (
      <div>
        <TemplateHeader template="MASTERY GATE" subtitle="Complete" />
        <div className="dark-card" style={{ textAlign: "center" }}>
          <p style={{ fontSize: "48px", marginBottom: "8px" }}>{passed ? "🏆" : "📚"}</p>
          <h2 style={{ color: "white", fontFamily: "Arial", fontSize: "24px", marginBottom: "8px" }}>
            {score} / {total}
          </h2>
          <p style={{ color: passed ? "#58D68D" : "#F1948A", fontFamily: "Arial", fontSize: "16px" }}>
            {passed ? "Mastery Achieved!" : "Keep practising — you're getting there!"}
          </p>
        </div>
        <button className="btn-primary" onClick={handleContinue}
          style={{ width: "100%", padding: "14px", marginTop: "16px" }}>
          Continue to Project Planning →
        </button>
      </div>
    )
  }

  return (
    <div>
      <TemplateHeader template="MASTERY GATE" subtitle={`Round ${round + 1} of ${MASTERY_ROUNDS.length}`} />

      {/* Subtopic progress pills */}
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap", marginBottom: "16px" }}>
        {SUBTOPICS.map(st => (
          <span key={st.key} style={{ ...PILL_STYLE, ...pillColors(subtopicStatus[st.key]) }}>
            {st.label}
          </span>
        ))}
      </div>

      <div className="card" style={{ background: "#1A5276", marginBottom: "16px" }}>
        <div style={{ display: "flex", justifyContent: "space-between" }}>
          <p style={{ color: "white", fontFamily: "Arial", fontSize: "13px" }}>
            Level: <strong>{MASTERY_ROUNDS[round].level.toUpperCase()}</strong>
          </p>
          <p style={{ color: "#E87722", fontFamily: "Arial", fontSize: "13px", fontWeight: "bold" }}>
            Score: {score}/{round}
          </p>
        </div>
      </div>

      {question && (
        <QuestionCard question={question} onAnswer={handleAnswer} loading={checking} />
      )}

      {/* isLast shows "See My Results →" on the final round */}
      {feedback && (
        <FeedbackCard
          feedback={feedback}
          onNext={handleNext}
          isLast={round === MASTERY_ROUNDS.length - 1}
        />
      )}
    </div>
  )
}
